import LogUtils, EnvironmentChecker
import os, json, subprocess

DEBUG = True

class ConfigParser:

    TAG = "ConfigParser"
    __IMAGE_DIR = os.path.join(os.getcwd(), "Images")
    __KEY_DIR = os.path.join(os.getcwd(), "Core", "currentKeySet")

    def __init__(self, logger = None) -> None:
        if not logger:
            self.myLogger = LogUtils.LogUtils()
            self.myLogger.log("W", "Logger not given, created an instance just now.", "ConfigParser")
        else:
            self.myLogger = logger
        self.myLogger.log("I", "Instance of ConfigParser successfully created.", "ConfigParser")

    def logIfDebug(self, logLevel = "V", 
                logStr = "Default log generated by logIfDebug"):
        self.myLogger.log(logLevel, logStr, "ImageInfoUtils")

    def getImageList(self,
                     fileDir = os.path.join(os.getcwd(),
                                            "Core",
                                            "currentConfigs",
                                            "imageList.txt")) -> list[str]:
        '''
        getImageList reads config file from assigned directory and returns a list contains image file's **NAME**.
        
        :param fileDir: The directory of config file.
        :return: A list contains partition file's **NAME**.
        :rtype: list[str]
        '''
        try:
            with open(fileDir, "r") as myFile:
                self.logIfDebug(logStr = "Successfully opened config file.")
                skipList = ["#", " ", "\n"]
                imageList = []
                fileLines = myFile.readlines()
                for fileReader in fileLines:
                    if fileReader[0] in skipList or len(fileReader) == 0:
                        self.logIfDebug(logStr = "Skipping line: " + fileReader.strip("\n"))
                    else:
                        fileReader = fileReader.strip("\n")
                        self.logIfDebug(logStr = "Image name to be appended: " + fileReader + ".img")
                        imageList.append(fileReader)
        except FileNotFoundError:
            self.myLogger.log("E", "File not found! Check your \"currentConfigs\" dir.")
            raise FileNotFoundError
        return imageList
    
    def buildSingleAvbtoolCommand(self, singleConfigDict : dict):
        """
        Generate AVBTool command for a single image from dictionary given.
        
        :param singleConfigDict: Config directory. Contains image name, rollback index, etc.
        :return: A dictionary contains command args accepted by subprocess.run()
        :rtype: dict
        :see: Core/ImageInfoUtils.py
        """
        isVbmeta = False
        if "vbmeta" in singleConfigDict["Image File"].lower():
            isVbmeta = True
        # Determine python and script file
        commandHeader = EnvironmentChecker.EnvironmentChecker.detect_python_command()
        if commandHeader is None:
            raise RuntimeError("Unable to find proper Python")
        commandList = [commandHeader, os.path.join(os.getcwd(), "Core", "avbtool.py")]
        # Detect image type and take proper action
        if isVbmeta:
            self.myLogger.log("I", "Generating VBMeta generation command for " + singleConfigDict["Image File"] + ".", self.TAG)
            commandList.append("make_vbmeta_image")
            commandList.extend(["--output", os.path.join(self.__IMAGE_DIR, singleConfigDict["Image File"])])
            # Add command for chain partition
            if len(singleConfigDict["Chain"]) != 0: # If there is/are chain partition(s) need to be added
                for i in range(len(singleConfigDict["Chain"])):
                    commandList.extend(["--chain_partition",
                                        singleConfigDict["Chain"][i]
                                        + os.path.join(self.__KEY_DIR, singleConfigDict["Chain partition key"][i])])
            # Add command for other partitions to be included
            for i in ["Hash", "Hashtree"]:
                if len(singleConfigDict[i]) != 0: # If this type of partition do exist
                    for j in singleConfigDict[i]:
                        if not os.path.exists(os.path.join(self.__IMAGE_DIR, j + ".img")):
                            raise RuntimeError("Required image %s not found!"%(os.path.join(self.__IMAGE_DIR, j + ".img")))
                        commandList.extend(["--include_descriptors_from_image",
                                            os.path.join(self.__IMAGE_DIR, j + ".img")])
        else:
            self.myLogger.log("I", "Generating normal image signing command for " + singleConfigDict["Image File"] + ".", self.TAG)
            if singleConfigDict["Descriptor Type"] == "Hash":
                self.myLogger.log("I", "Adding hash footer command.", self.TAG)
                commandList.append("add_hash_footer")
                commandList.extend(["--partition_size", singleConfigDict["Image size"]])
            else:
                self.myLogger.log("I", "Adding hashtree footer command.", self.TAG)
                commandList.append("add_hashtree_footer")
                if os.name == "nt":
                    commandList.append("--do_not_generate_fec")
                    self.myLogger.log("W", "Running on Windows, skipping FEC encoding.", self.TAG)
            # Add common args for non-vbmeta images
            if not os.path.exists(os.path.join(self.__IMAGE_DIR, singleConfigDict["Image File"])):
                raise RuntimeError("Required image %s not found!"%(os.path.join(self.__IMAGE_DIR, singleConfigDict["Image File"])))
            commandList.extend(["--image", os.path.join(self.__IMAGE_DIR, singleConfigDict["Image File"]),
                "--partition_name", singleConfigDict["Partition Name"],
                "--salt", singleConfigDict["Salt"]])
        # Add shared configs
        if singleConfigDict["Algorithm"] != "NONE":
            commandList.extend(["--algorithm", singleConfigDict["Algorithm"],
                                "--key", os.path.join(self.__KEY_DIR, singleConfigDict["Public key file"])])
        else:
            commandList.extend(["--hash_algorithm", singleConfigDict["Hash Algorithm"]])
        commandList.extend(["--rollback_index", singleConfigDict["Rollback Index"]])
        for i in singleConfigDict["Props"]:
            commandList.extend(["--prop", i + ":" + singleConfigDict["Props"][i]])
        self.myLogger.log("I", "Success.", self.TAG)
        return commandList
    
    def getConfigName(self,
                      configDir = os.path.join(os.getcwd(), "Core", "currentConfigs")) -> str:
        """
        Get the name of a config by parsing config.cfg.

        Return the name of current config if arg `configDir` is not given.

        Will return nothing when config file cannot be reached.

        :param configDir: The directory of config.cfg. DO NOT post filename.
        :type configDir: str
        :return: The name of config.
        :rtype: str
        """
        try:
            with open(os.path.join(configDir, "config.cfg"), "r") as myFile:
                fileLines = myFile.readlines()
                self.myLogger.log("D", str(fileLines), self.TAG)
                splittedLine = []
                for i in fileLines:
                    splittedLine = i.split(":")
                    if splittedLine[0] == "Config Name":
                        return splittedLine[1].lstrip(" ").rstrip("\n")
                else:
                    self.myLogger.log("W", "Found config file, but file doesn't contain valid info.", self.TAG)
                    return ""
        except FileNotFoundError:
            self.myLogger.log("W", "Config file not found!", self.TAG)
            return ""
    
    def json2Dic(self, imageConfigFileDir = 
                 os.path.join(os.getcwd(), "Core", "currentConfigs", "imageInfo.json")) -> dict:
        """
        Parse JSON object to Python dictionary.

        :param imageConfigFileDir: The directory of config file, you can freely include filename or not.
        If not, method will use default value imageInfo.json.
        :type imageConfigFileDir: str
        :return: Dictionary contains JSON content.
        :rtype: dict
        """
        if imageConfigFileDir.endswith("/") or imageConfigFileDir.endswith("\\"):
            imageConfigFileDir += "imageInfo.json"
        with open(imageConfigFileDir, "r") as myFile:
            configDic : dict = json.load(myFile)
        return configDic