import LogUtils, KeyDirUtils, ConfigParser, EnvironmentChecker
import subprocess, os, copy, json

class ImageInfoUtils:

    def __init__(self, logger = None) -> None:
        self.TAG = "ImageInfoUtils"
        if not logger:
            self.myLogger = LogUtils.LogUtils()
            self.myLogger.log("W", "Logger not given, created an instance just now.", self.TAG)
        else:
            self.myLogger = logger
        self.myLogger.log("I", "Instance of ImageInfoUtils successfully created.", self.TAG)

    def logIfDebug(self, logLevel = "V", 
                logStr = "Default log generated by logIfDebug"):
        self.myLogger.log(logLevel, logStr, self.TAG)
    
    def checkImageExists(self, imageInfoList : list[str], imageDir = None):
        if imageDir is None:
            imageDir = os.path.join(os.getcwd(), "Images")
        existingImages = []
        for i in os.listdir(imageDir):
            if i.endswith(".img"):
                existingImages.append(i[:-4:])
            else:
                existingImages.append(i)
        existingImages.sort()
        imageInfoList.sort()
        setExisting = set(existingImages)
        setImageInfoList = set(imageInfoList)
        if setExisting == setImageInfoList:
            self.myLogger.log("D", str((True, "EQUAL", setExisting)), self.TAG)
            return (True, "EQUAL", setExisting)
        else:
            self.myLogger.log("D", str((False, setExisting.difference(setImageInfoList), setExisting, setImageInfoList)), self.TAG)
            if len(existingImages) > len(imageInfoList):
                self.myLogger.log("W", "MORE", self.TAG)
                return (False, "MORE", setExisting.difference(setImageInfoList), setExisting, setImageInfoList)
            if len(existingImages) < len(imageInfoList):
                self.myLogger.log("W", "LESS", self.TAG)
                return (False, "LESS", setExisting.difference(setImageInfoList), setExisting, setImageInfoList)
            else:
                self.myLogger.log("W", "DIFF", self.TAG)
                return (False, "DIFF", setExisting.difference(setImageInfoList), setExisting, setImageInfoList)
            

    def readImageInfo(self, imageName : str) -> str:
        '''
        Read footer of a SINGLE IMAGE. retval: string
        Will raise RuntimeException when operation cannot be finished due to wrong OS or ENOENT.
        
        :param imageName: image file's name, method will auto correct it to ".img".
        '''
        if not imageName.endswith(".img"):
            imageName += ".img"

        self.myLogger.log("D", "Reading image info: " + imageName)

        commandHeader = EnvironmentChecker.EnvironmentChecker.detect_python_command()

        if commandHeader is None:
            self.myLogger.log("W", "Unable to find proper Python")
            raise RuntimeError("Unable to find proper Python")

        commandList = [commandHeader,
                       os.path.join(os.getcwd(), "Core", "avbtool.py"),
                       "info_image",
                       "--image",
                       os.path.join(os.getcwd(), "Images", imageName)]

        # Add capture_output and text args to ensure object "result" contains output content    
        result = subprocess.run(commandList, capture_output=True, text=True)
        if result.returncode == 0:
            self.logIfDebug("V", "Successfully executed \"avbtool info_image\" command.")
            return str(result.stdout)
        else:
            self.logIfDebug("W", "avbtool.py returned non-zero exit code. Check next line of log for detailed information.")
            # Process standard error, we don't need usage tips.
            errorContent = str(result.stderr)
            if "does not look like" in errorContent:
                self.myLogger.log("W", "You are reading a image without avb footer.", "ImageInfoUtils")
                self.myLogger.log("D", "Maybe AVBPowerTool encountered unhandled exception in signing stage.")
                self.myLogger.log("D", "Or much simpler, the problem is in image itself.")
                raise RuntimeError("Non-vbmeta image.")
            errorContent = errorContent[errorContent.find("error:"):].strip("\n")
            self.myLogger.log("W", "Error info: " + errorContent, "ImageInfoUtils")
            # Provide special tip for ERRNO 2.
            if "Errno 2" in errorContent:
                self.myLogger.log("W", "Image file not found. Check your image dir.")
                if os.name == "nt":            
                    self.myLogger.log("W", "You are running this program on Windows, Linux environment is recommended.")
            raise RuntimeError("avbtool.py encountered an issue, fix it and restart the program.")

    def __imageInfoParser(self, imageInfoString : str, isVBmetaImage = False) -> dict:
        '''
        Convert string result to a dictionary that contains footer info.
        Will call private method __generateConfigDict() or __generateConfigDictVB() to finally generate result dictionary.
        isVBmetaImage is an optional arg that allows you to parse image as vbmeta format.
        '''
        if isVBmetaImage:
            self.myLogger.log("I", "Processing a VBMeta image.", "imageInfoParser")
        colonPosition = -1
        imageInfoList = imageInfoString.split("\n")
        self.logIfDebug("V", "Step 1, split image info string into list by symbol \\n:")
        for i in imageInfoList:
            self.logIfDebug("V", i)
        self.logIfDebug("V", "Step2, delete useless spaces and parse them into key-value pairs.")
        propCount = 0
        '''
        Less information are required when creating a vbmeta image.
        Thus allowing we process them in this method instead of extracting this logic.
        '''
        if isVBmetaImage:
            # The sequence of list "Chain" and list "Chain partition key" are the same.
            # You can easily use one "for" loop to convert usable "include chain partition" command line
            resultDic = {"Chain" : [], # Store chain partition name and rollback index location
                         "Chain partition key" : [], # Store chain partition's key file name (with relative path)
                         "Hash" : [], # Store partitions with hash descriptors that added to vbmeta image
                         "Hashtree" : [], # Store partitions with hashtree descriptors that added to vbmeta image
                         "Algorithm" : "", # Store vbmeta's hash algorithm
                         "Public key (sha1)" : "" # Store vbmeta's public key SHA1
                         }
            infoListLength = len(imageInfoList)
            encounterStringDesc = False # Has encountered string "Descriptors"? This string indicates the beginning of "other partitions' info"
            i = 0
            while i < infoListLength:
                if encounterStringDesc:
                    if "Chain" in imageInfoList[i]:
                        self.logIfDebug("V", "Found chain partition.")
                        # In case the output sequence changes, use loop instead of hard-coded position
                        # Find partition name
                        for j in range(i + 1, i + 5): # Each chain partition has a 4-line descriptor
                            if "Name" in imageInfoList[j]:
                                colonPosition = imageInfoList[j].find(":")
                                resultDic["Chain"].append(imageInfoList[j][colonPosition + 1:].strip(" "))
                                break
                        # Find rollback index location
                        for j in range(i + 1, i + 5): # Each chain partition has a 4-line descriptor
                            if "Rollback Index Location" in imageInfoList[j]:
                                colonPosition = imageInfoList[j].find(":")
                                # always add rollback index info to the last element (which is appended by the previous "for" loop.)
                                resultDic["Chain"][-1] += ":" + imageInfoList[j][colonPosition + 1:].strip(" ") + ":"
                                break
                        # Find public key SHA1
                        for j in range(i + 1, i + 5):
                            self.logIfDebug("V", "Process chain partition key.")
                            if "Public key" in imageInfoList[j]:
                                colonPosition = imageInfoList[j].find(":")
                                tempDic = {"Public key (sha1)" : imageInfoList[j][colonPosition + 1:].strip(" ")}
                                resultDic["Chain partition key"].append(self.__autoDetectKeyBin(self.__autoDetectKeyFile(tempDic)["Public key file"]))
                        i += 5
                    elif "Hash descriptor" in imageInfoList[i]:
                        self.logIfDebug("V", "Found hash descriptor.")
                        for j in range(i + 1, i + 7): # Each partition with a hash desc has a 6-line descriptor
                            if "Name" in imageInfoList[j]:
                                colonPosition = imageInfoList[j].find(":")
                                resultDic["Hash"].append(imageInfoList[j][colonPosition + 1:].strip(" "))
                                break
                        i += 7
                    elif "Hashtree descriptor" in imageInfoList[i]:
                        self.logIfDebug("V", "Found hashtree descriptor.")
                        for j in range(i + 1, i + 15): # Each partition with a hashtree desc has a 14-line descriptor
                            if "Name" in imageInfoList[j]:
                                colonPosition = imageInfoList[j].find(":")
                                resultDic["Hashtree"].append(imageInfoList[j][colonPosition + 1:].strip(" "))
                                break
                        i += 15
                    elif "Prop" in imageInfoList[i]:
                        self.logIfDebug("V", "Prop string detected.")
                        colonPosition = imageInfoList[i].find(":")
                        resultDic["Prop" + str(propCount)] = imageInfoList[i][colonPosition + 1:].strip(" ")
                        propCount += 1
                        i += 1
                    else:
                        i += 1
                else:
                    if "Descriptors:" in imageInfoList[i]:
                        encounterStringDesc = True
                    elif "Algorithm" in imageInfoList[i]:
                        resultDic["Algorithm"] = imageInfoList[i][imageInfoList[i].find(":") + 1:].strip(" ")
                    elif "Rollback" in imageInfoList[i] and "Location" not in imageInfoList[i]:
                        resultDic["Rollback Index"] = imageInfoList[i][imageInfoList[i].find(":") + 1:].strip(" ")
                    elif "Public key (sha1)" in imageInfoList[i]:
                        resultDic["Public key (sha1)"] = imageInfoList[i][imageInfoList[i].find(":") + 1:].strip(" ")
                    i += 1
        else:
            resultDic = {}
            for i in imageInfoList:
                colonPosition = -1
                colonPosition = i.find(":")
                if colonPosition != -1:
                    self.logIfDebug("V", "Find separator in line: " + i)
                    if "Prop" in i[:colonPosition].strip(" "):
                        self.logIfDebug("V", "Prop string detected.")
                        resultDic[i[:colonPosition].strip(" ") + str(propCount)] = i[colonPosition + 1:].strip(" ")
                        propCount += 1
                    else:
                        resultDic[i[:colonPosition].strip(" ")] = i[colonPosition + 1:].strip(" ")
        self.logIfDebug("I", "Successfully parsed image info.")
        self.logIfDebug("I", "Step3, remove unnecessary key-value pairs and add some post process.")
        if isVBmetaImage:
            # Only have to process prop
            resultDic = self.__generateConfigDictVB(resultDic)
        else:
            # Remove unnecessary value.
            # Too many valid values, better process them in a separated method.
            resultDic = self.__generateConfigDict(resultDic)
        resultDic = self.__autoDetectKeyFile(resultDic)
        return resultDic
    
    # Process props, put them into a subDictionary.
    def __generateConfigDictVB(self, imageInfoDic : dict) -> dict:
        resultDic = imageInfoDic
        propList = []
        resultDicCopy = copy.deepcopy(resultDic)
        # Remove key-value pairs with empty/wrong value, process props, and detect descriptor type
        for i in resultDicCopy:
            if "Prop" in i:
                propList.append(resultDic[i])
                resultDic.pop(i)
        arrowPos = -1
        propDic = {}
        for i in propList:
            arrowPos = -1
            arrowPos = i.find("->")
            if arrowPos != -1:
                propDic[i[: arrowPos - 1]] = i[arrowPos + 4 : -1]
        resultDic["Props"] = propDic
        return resultDic

    def __generateConfigDict(self, imageInfoDic : dict) -> dict:
        '''
        Provide a dictionary with necessary data:
        Actual Image Size,
        Public Key,
        Algorithm,
        Rollback Index,
        Hash Algorithm,
        Partition Name,
        Salt,
        Prop (Saved in a sub-dictionary),
        Descriptor Type [Hash|Hashtree]
        '''
        resultDic = imageInfoDic
        # Remove useless keys
        excludedKeyList = ["Footer version", "Original image size", "VBMeta offset",
                           "VBMeta size", "Minimum libavb version", "Header Block",
                           "Authentication Block", "Auxiliary Block", "Flags",
                           "Release String", "Digest", "Flags",
                           "Descriptors", "Rollback Index Location"]
        for i in excludedKeyList:
            try:
                resultDic.pop(i)
            except Exception as e:
                self.logIfDebug("W", str(e))
        hasEncounterString = False # Has encountered string "hash(tree) descriptor"
        descriptorType = "" # Hash or Hashtree
        propList = []
        resultDicCopy = copy.deepcopy(resultDic)
        # Remove key-value pairs with empty/wrong value, process props, and detect descriptor type
        for i in resultDicCopy:
            if i.lower() == "hash descriptor" or i.lower() == "hashtree descriptor":
                hasEncounterString = True
                if "hashtree" in i.lower():
                    descriptorType = "Hashtree"
                else:
                    descriptorType = "Hash"
                resultDic.pop(i)
            elif i == "Image Size":
                if hasEncounterString:
                    # Preserved logic, maybe Google will fix typo in newer version of avbtool.py?
                    # They use "Image size" in avbtool 1.3 to indicate actual image size.
                    resultDic.pop(i)
                else:
                    resultDic[i] = resultDic[i][:-5]
            elif i == "Image size":
                resultDic[i] = resultDic[i][:-6]
            elif "Prop" in i:
                propList.append(resultDic[i])
                resultDic.pop(i)
        resultDic["Descriptor Type"] = descriptorType
        arrowPos = -1
        propDic = {}
        for i in propList:
            arrowPos = -1
            arrowPos = i.find("->")
            if arrowPos != -1:
                propDic[i[: arrowPos - 1]] = i[arrowPos + 4 : -1]
        resultDic["Props"] = propDic
        return resultDic
    
    def __autoDetectKeyFile(self, imageInfoDic : dict) -> dict:
        # Create result dictionary
        imageInfoDicCopy = copy.deepcopy(imageInfoDic)
        # Make sure the key cache exists
        if not os.path.exists(os.path.join(os.getcwd(),
                                           "Core",
                                           "currentKeySet",
                                           "keyCache.cache")):
            keyDirUtils = KeyDirUtils.KeyDirUtils()
            keyDirUtils.generateKeyFileCache()
        # Start detection.
        with open(os.path.join(os.getcwd(),
                                "Core",
                                "currentKeySet",
                                "keyCache.cache")) as myFile:
            fileWithSha1 = myFile.readlines()
            sha1List = []
            '''
            The structure of sha1List:
            [
            [filename1, sha1_1],
            [filename2, sha1_2],
            ...
            ]
            '''
            for i in range(len(fileWithSha1)):
                sha1List.append(fileWithSha1[i].strip("\n").split(", "))
            for j in imageInfoDic:
                # Look for Public key value
                if j == "Public key (sha1)":
                    self.myLogger.log("V", "Public key SHA1: " + imageInfoDic[j], "autoDetectKeyFile")
                    # Start auto-matching once found public key SHA1
                    for k in range(len(sha1List)):
                        if sha1List[k][1] == imageInfoDic[j]:
                            self.myLogger.log("V", "Key file: " + sha1List[k][0], "autoDetectKeyFile")
                            imageInfoDicCopy["Public key file"] = sha1List[k][0]
            return imageInfoDicCopy
    
    def __autoDetectKeyBin(self, imageInfoDic) -> dict:
        return imageInfoDic[:-4] + "_pub.bin"

    # Private method to read image info, will return a dicrionary, will not save result to file.
    def __readImageInfoBatchPriv(self, imageList : list[str]) -> dict:
        mImageInfoString = ""
        superResultDic = {} # Can be converted into JSON.
        for i in imageList:
            try:
                mImageInfoString = self.readImageInfo(imageName = i)
            except RuntimeError as e:
                continue
            if "vbmeta" in i:
                superResultDic[i] = self.__imageInfoParser(mImageInfoString, True)
            else:
                superResultDic[i] = self.__imageInfoParser(mImageInfoString, False)
            superResultDic[i]["Image File"] = i + ".img"
        #print(superResultDic)
        self.myLogger.log("I", "Image info extraction ended successfully.")
        return superResultDic
    
    # Expose to outer world, will save result to file.
    def readImageInfoBatch(self, imageList : list[str]) -> None:
        self.saveResultToFile(self.__readImageInfoBatchPriv(imageList))

    def saveResultToFile(self, resultDict : dict) -> None:
        jsonString = json.dumps(resultDict, indent=4, sort_keys=True)
        with open(os.path.join(os.getcwd(),
                               "Core",
                               "currentConfigs",
                               "imageInfo.json"), "w+") as myFile:
            myFile.write(jsonString)
        self.myLogger.log("I", "Image info successfully written into "
                          + os.path.join(os.getcwd(),
                                        "Core",
                                        "currentConfigs",
                                        "imageInfo.json"), "saveResultToFile")

if __name__ == "__main__":
    myLogger = LogUtils.LogUtils()
    myImageInfoUtils = ImageInfoUtils()
    myConfigParser = ConfigParser.ConfigParser()
    imageList = myConfigParser.getImageList()
    myLogger.log("I", "================================================================================", "ImageInfoUtils")
    myLogger.log("I", "Image list read from config:", "ImageInfoUtils")
    for i in imageList:
        myLogger.log("I", i + ".img", "ImageInfoUtils")
    myLogger.log("I", "================================================================================", "ImageInfoUtils")
    myImageInfoUtils.readImageInfoBatch(imageList = imageList)